### ISSUE TITLE
Community Call flyer, needed by end of Monday 14th

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/Marketing-Ad-hoc#22]
**Scope:** We have just confirmed our two guest speakers for this Wednesday but due to covid having caused people to pull out in the past at the last minute, please can we share just the organisations they're representing.

**Details:** Please use Popcorn's current brand guidelines to create a graphic for this week's community call (I think there are templates for the size used).

Please add the following information: With special guests from BasinDAO and Sociocracy 3.0

You can find respective logos at: https://www.basin.global/ and https://sociocracy30.org/ 

I trust you to please use your designer skills to decide if just a logo is OK or if we need text stating the organisation names on the graphic too, and whether the graphic needs to read 'With special guests from' or just 'Special guests from' or 'With special guests (and then the logos etc.) Whatever looks the most readable and sits best on the graphic.

**Timescale:** Please complete by end of today. Thank you!

**Comment by FanFanDAO** [comment]
No identifiable SVG logo is available. A screenshot is taken and the small logo is cut out in order to be used for our fast turnaround. It is ok presented on a small scale so please provide a direct link to the SVG to be ideal. Also, requesting the brand asset from partners from the beginning would be my recommendation.

![community call 6.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1cdfadf7-c534-4812-8fdc-1c74d73b389e)
